name: Deploy / docker images

on:
  push:
    tags:
      - "*"

jobs:
  workflow-call:
    uses: ./.github/workflows/CI.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [workflow-call]
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT}} "cd ${{ secrets.WORK_DIR }} && make update-container portfolio && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
